apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status: {}

# deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-master
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins-master
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins-master
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          securityContext:
            runAsUser: 0
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: jenkins-docker-sock
              mountPath: "/var/run/docker.sock"
            - name: jenkins-docker
              mountPath: "/usr/bin/docker"

      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pvc
        - name: jenkins-docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: jenkins-docker
          hostPath:
            path: /usr/bin/docker
